# Generated by Django 3.0.5 on 2020-05-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PE', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='sample',
            fields=[
                ('firstname', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('rno', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
