# Generated by Django 3.0.5 on 2020-05-06 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PE', '0002_sample'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='firstname',
        ),
    ]
