# Generated by Django 3.0.5 on 2020-05-07 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PE', '0005_auto_20200507_0740'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('rno', models.IntegerField()),
            ],
        ),
    ]
